### ISSUE TITLE
dev mode - files not written to disk

### ISSUE THREAD

**Issue by zzroche** [ivarprudnikov/webpack-static-html-pages#2]
In dev mode doesn't create the .html files

**Comment by ivarprudnikov** [comment]
It is disabled by default in `webpack-dev-server`. In order to change it open `webpack.dev.js` and add  `writeToDisk`:

```
  devServer: {
    port: 8080,
    writeToDisk: true
  },
```

Documentation https://webpack.js.org/configuration/dev-server/#devserverwritetodisk-
