### ISSUE TITLE
css not inlined in head

### ISSUE THREAD

**Issue by gbishop** [ivarprudnikov/webpack-static-html-pages#3]
Forgive me if I'm missing something. Your article has been super useful in getting me started.

But when I clone your project and run npm run build, the css is not getting inlined into the head. In your article you say 

> Now after npm start you’ll see css inlined in the head element of html file. To add more styles just require them in Javascript file.

But I'm not getting that behavior. Instead it is generating a css file with hash and linking it.

**Comment by ivarprudnikov** [comment]
Thanks for raising the issue, I've fixed the ambiguity in the article. CSS file in-lining was expected behavior: 
https://github.com/ivarprudnikov/ivarprudnikov.com/commit/be951b748084458c781043ce8468b1ab2f75ddb5

**Comment by gbishop** [comment]
I take "inlining" to mean the CSS is included in a style tag. That is not what I'm seeing. Instead I'm seeing a .css file.
`webpack-static-html-pages (master)$ ls -l dist
total 60
-rw-rw-r-- 1 gb gb 1160 Jul 17 10:23 about.357031fef1413c69d4e1.js
-rw-rw-r-- 1 gb gb 4927 Jul 17 10:23 about.357031fef1413c69d4e1.js.map
-rw-rw-r-- 1 gb gb 2910 Jul 17 10:23 about.95ae9c69189370de57cf.css
-rw-rw-r-- 1 gb gb 1364 Jul 17 10:23 about.html
-rw-rw-r-- 1 gb gb 1168 Jul 17 10:23 contacts.357031fef1413c69d4e1.js
-rw-rw-r-- 1 gb gb 4936 Jul 17 10:23 contacts.357031fef1413c69d4e1.js.map
-rw-rw-r-- 1 gb gb 2908 Jul 17 10:23 contacts.d5304bf6e50ddfbc157f.css
-rw-rw-r-- 1 gb gb 1379 Jul 17 10:23 contacts.html
-rw-rw-r-- 1 gb gb 1680 Jul 17 10:23 index.357031fef1413c69d4e1.js
-rw-rw-r-- 1 gb gb 5312 Jul 17 10:23 index.357031fef1413c69d4e1.js.map
-rw-rw-r-- 1 gb gb 2910 Jul 17 10:23 index.64660c4144d3f5165c2e.css
-rw-rw-r-- 1 gb gb 1374 Jul 17 10:23 index.html`

`<!DOCTYPE html>
<html>
<head>
  <title>My homepage</title>
  <meta charset="UTF-8">
  <meta http-equiv="cache-control" content="no-cache"/>
  <meta http-equiv="pragma" content="no-cache"/>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="viewport"
        content="width=device-width,user-scalable=0,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link href="index.64660c4144d3f5165c2e.css" rel="stylesheet"></head>`

Am I missing something? Thanks.

**Comment by ivarprudnikov** [comment]
It is not expected to see _inlined_ CSS in a sense you're referring to. I've replaced usage of `inlined` to `injected` so that sentence now reads:
> Now after `npm start` you’ll see link to `css` stylesheet injected in the `head` element of an `html` file. To add more stylesheets just _require()_ them in _Javascript_ file.

**Comment by gbishop** [comment]
Ah, I see. I misunderstood. Thanks for the quick response and sorry for the
noise. Your repo and article have been a great help.
