### ISSUE TITLE
Using images

### ISSUE THREAD

**Issue by El-Tommy** [ivarprudnikov/webpack-static-html-pages#403]
I didn't quite understand the use of images.

I'm putting the images inside the `./src/img` folder. Every time I need to use an image on a page, do I need to do a `<%= require('../img/image-name.svg') %>` ?

And how do I put images inside the partials? Even with require I couldn't make it work.

**Comment by RandyBooth** [comment]
Have you tried this way? Just one '.'

<%= require('./img/image-name.svg') %>

**Comment by ivarprudnikov** [comment]
"about" page template contains 2 examples on how to add images https://github.com/ivarprudnikov/webpack-static-html-pages/blob/master/src/page-about/tmpl.html
